version: "3"

services:
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/srv/www
    ports:
      - 80:80
      - 9000:9000
    environment:
      - _buildEnv=local
  database:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hackathon
    ports:
      - 3306:3306
